databases:
  - name: radarhub-db
    databaseName: radar_sebrae
    user: radar
    plan: free

services:
  - type: web
    name: radarhub-api
    runtime: docker
    plan: free
    dockerfilePath: apps/api/Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        fromDatabase:
          name: radarhub-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://radarhub-web.vercel.app
